name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: contains skip
        run: echo "TO BE SKIPPED"
        if: ! (contains(join(github.event.commits.*.message), '#skip'))
      - name: does not contains skip
        run: echo "NOT TO BE SKIPPED"
        if: contains(join(github.event.commits.*.message), '#skip')
